branches:
  only:
  - master

language: objective-c
osx_image: xcode11

script:
- xcodebuild -project MacMediaKeyForwarder.xcodeproj -scheme "MacMediaKeyForwarder" build

after_success:
- bash <(curl -s https://codecov.io/bash)  -J 'MacMediaKeyForwarder'
